# Generated by Django 5.0 on 2024-01-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_penulis_books_nama_kopi_remove_books_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Kopi',
        ),
    ]
