# Generated by Django 5.0 on 2024-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_books_kopi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kopi',
            name='gambar_kopi',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
